use super::{RECURSION, compile};

#[test]
fn bad_patterns_give_the_messages_of_python() {
    for (pattern, message) in [
        ("a{5,3}", "min repeat greater than max repeat at position 2"),
        ("a{99999999999}", "the repetition number is too large"),
        ("(?<=a+)b", "look-behind requires fixed-width pattern"),
        ("x**", "multiple repeat at position 2"),
        ("(?i", "missing -, : or ) at position 3"),
        ("(?x", "missing -, : or ) at position 3"),
        ("(?P<1>a)", "bad character in group name '1' at position 4"),
        ("(?P=n)", "unknown group name 'n' at position 4"),
        ("\\1", "invalid group reference 1 at position 1"),
        ("(a)\\2", "invalid group reference 2 at position 4"),
        ("a)", "unbalanced parenthesis at position 1"),
        ("[z-a]", "bad character range z-a at position 1"),
        ("\\q", "bad escape \\q at position 0"),
        ("\\x1", "incomplete escape \\x1 at position 0"),
        ("(?<x)", "unknown extension ?<x at position 1"),
        ("(?#abc", "missing ), unterminated comment at position 0"),
        ("(?im-i:a)", "bad inline flags: flag turned on and off at position 6"),
        ("a(?i)b", "global flags not at the start of the expression at position 1"),
        ("(?u)(?a)x", "ASCII and UNICODE flags are incompatible"),
        ("\\N{FOO}", "undefined character name 'FOO' at position 0"),
        ("\\N", "missing { at position 2"),
        ("\\8", "invalid group reference 8 at position 1"),
        ("(?(2)a|b)", "invalid group reference 2 at position 3"),
        ("(a)(?(1)a|b|c)", "conditional backref with more than two branches at position 11"),
        ("a\nb)", "unbalanced parenthesis at position 3 (line 2, column 2)"),
        ("(?P<a>x)(?P<a>y)", "redefinition of group name 'a' as group 2; was group 1 at position 12"),
        ("(?P<a b>x)", "bad character in group name 'a b' at position 4"),
        ("(?P", "unexpected end of pattern at position 3"),
        ("(?", "unexpected end of pattern at position 2"),
        ("(?-", "missing flag at position 3"),
        ("(?i-", "missing flag at position 4"),
        ("(?i-:x)", "missing flag at position 4"),
        ("\\", "bad escape (end of pattern) at position 0"),
        ("[a", "unterminated character set at position 0"),
        ("[a-", "unterminated character set at position 0"),
        ("[\\d-z]", "bad character range \\d-z at position 1"),
        ("*", "nothing to repeat at position 0"),
        ("^*", "nothing to repeat at position 1"),
        ("\\b*", "nothing to repeat at position 2"),
        ("(?<=a|bc)", "look-behind requires fixed-width pattern"),
        ("(?<=\\1)(a)", "invalid group reference 1 at position 5"),
        ("x{1,2}{3}", "multiple repeat at position 6"),
        ("a{2}?+", "multiple repeat at position 5"),
        ("\\u12", "incomplete escape \\u12 at position 0"),
        ("\\U0011ffff", "bad escape \\U0011ffff at position 0"),
        ("\\777", "octal escape value \\777 outside of range 0-0o377 at position 0"),
        ("[\\777]", "octal escape value \\777 outside of range 0-0o377 at position 1"),
        ("[\\A]", "bad escape \\A at position 1"),
        ("(?L)a", "bad inline flags: cannot use 'L' flag with a str pattern at position 3"),
        ("(?-t:a)", "bad inline flags: cannot turn off global flag at position 4"),
        ("(?i:a)(?x)", "global flags not at the start of the expression at position 6"),
        ("(", "missing ), unterminated subpattern at position 0"),
        ("((a)", "missing ), unterminated subpattern at position 0"),
        ("[\\x41-\\x40]", "bad character range \\x-\\x at position 5"),
        ("(?P<a>a)(?P=a", "missing ), unterminated name at position 12"),
        ("(?Px)", "unknown extension ?Px at position 1"),
        ("(?<", "unexpected end of pattern at position 3"),
        ("(a)(?<=(?(1)b|cc))", "look-behind requires fixed-width pattern"),
        ("(?au:a)", "bad inline flags: flags 'a', 'u' and 'L' are incompatible at position 4"),
        ("(?i-a:a)", "bad inline flags: cannot turn off flags 'a', 'u' and 'L' at position 5"),
        ("a\\", "bad escape (end of pattern) at position 1"),
        ("(?(0)a)", "bad group number at position 3"),
        ("(?(a)b)", "unknown group name 'a' at position 3"),
        ("(?(1a)b)", "bad character in group name '1a' at position 3"),
        ("(?x)a #c\n)", "unbalanced parenthesis at position 9 (line 2, column 1)"),
        ("(?<=a)(?<!b)(?=c", "missing ), unterminated subpattern at position 12"),
        ("{3}", "nothing to repeat at position 0"),
        ("a|*", "nothing to repeat at position 2"),
        ("(?:", "missing ), unterminated subpattern at position 0"),
        ("[]", "unterminated character set at position 0"),
        ("[^]", "unterminated character set at position 0"),
        ("(?-i)", "missing : at position 4"),
        ("(?i-x", "missing : at position 5"),
        ("(?i-x;", "missing : at position 5"),
        ("(?x-#", "missing flag at position 4"),
        ("(?ib)", "unknown flag at position 3"),
    ] {
        assert_eq!(compile(pattern, 986).err().as_deref(), Some(message), "{pattern:?}");
    }
}

#[test]
fn patterns_that_python_accepts_compile() {
    for pattern in ["(?<=(a))\\1", "[]-a]", "(?t)a"] {
        assert!(compile(pattern, 986).is_ok(), "{pattern:?}");
    }
}

#[test]
fn the_search_gives_the_result_of_python() {
    let wrong = [
        ("fusion.*", "fusion.1", true),
        ("fusion.*", "copy", false),
        ("^fusion$", "fusion", true),
        ("^fusion$", "fusion\n", true),
        ("^fusion$", "fusion\n\n", false),
        ("^fusion$", "xfusion", false),
        ("a$b", "a\nb", false),
        ("a$b", "ab", false),
        ("a\\Z", "a", true),
        ("a\\Z", "a\n", false),
        ("a{", "a{", true),
        ("a{", "a", false),
        ("a{,2}b", "aab", true),
        ("a{,2}b", "b", true),
        ("a{,2}b", "a{,2}b", true),
        ("x{1,}y", "xxy", true),
        ("x{1,}y", "y", false),
        ("a{}", "a{}", true),
        ("a{}", "a", false),
        ("(?<=a)b", "ab", true),
        ("(?<=a)b", "cb", false),
        ("(?<!a)b", "ab", false),
        ("(?<!a)b", "cb", true),
        ("a(?=b)", "ab", true),
        ("a(?=b)", "ac", false),
        ("a(?!b)", "ab", false),
        ("a(?!b)", "ac", true),
        ("(a)\\1", "aa", true),
        ("(a)\\1", "ab", false),
        ("(?P<x>a)(?P=x)", "aa", true),
        ("(?P<x>a)(?P=x)", "ab", false),
        ("(a)?(?(1)b|c)", "ab", true),
        ("(a)?(?(1)b|c)", "c", true),
        ("(a)?(?(1)b|c)", "a", false),
        ("(?>a+)a", "aaa", false),
        ("a++a", "aaa", false),
        ("a*+b", "aab", true),
        ("(?i)FUSION", "fusion", true),
        ("(?i:A)b", "ab", true),
        ("(?i:A)b", "aB", false),
        ("(?s).", "\n", true),
        (".", "\n", false),
        (".", "x", true),
        ("(?m)^b", "a\nb", true),
        ("^b", "a\nb", false),
        ("\\w+", "\u{e9}", true),
        ("\\w+", "_", true),
        ("\\w+", "-", false),
        ("\\w+", "\u{301}", false),
        ("\\w+", "\u{b2}", true),
        ("(?a)\\w", "\u{e9}", false),
        ("(?a)\\w", "e", true),
        ("\\s", "\u{1c}", true),
        ("\\s", "\u{a0}", true),
        ("\\s", "x", false),
        ("(?a)\\s", "\u{a0}", false),
        ("(?a)\\s", " ", true),
        ("\\bfoo\\b", "a foo b", true),
        ("\\bfoo\\b", "afoob", false),
        ("\\bfoo\\b", "foo", true),
        ("\\Bo", "foo", true),
        ("\\Bo", "o", false),
        ("\\B", "", false),
        ("\\B", "x", false),
        ("\\b", "", false),
        ("[\\w-]+", "a-b", true),
        ("[^\\W\\d]", "1", false),
        ("[^\\W\\d]", "a", true),
        ("[\\s\\d]", " ", true),
        ("[\\s\\d]", "5", true),
        ("[\\s\\d]", "x", false),
        ("\\d", "\u{663}", true),
        ("\\d", "x", false),
        ("[a-]", "-", true),
        ("[]a]", "]", true),
        ("[^]a]", "]", false),
        ("[^]a]", "b", true),
        ("\\x41\\u0042\\U00000043", "ABC", true),
        ("\\101", "A", true),
        ("\\0", "\u{0}", true),
        ("[\\b]", "\u{8}", true),
        ("a|b|", "", true),
        ("a|b|", "c", true),
        ("(?x) a b # c", "ab", true),
        ("(?x) a b # c", "a b", false),
        ("(?x)[ ]", " ", true),
        ("(?#c)a", "a", true),
        ("a(?#c)*", "aaa", true),
        ("a(?#c)*", "", true),
        ("\\.", ".", true),
        ("\\.", "x", false),
        ("\\-", "-", true),
        ("(?:a*)*b", "b", true),
        ("all-reduce|all-gather", "all-gather.1", true),
        ("all-reduce|all-gather", "reduce", false),
        ("(?i)[a-c]", "B", true),
        ("(?i)\u{e9}", "\u{c9}", true),
        ("(?ai)\u{e9}", "\u{c9}", false),
        ("[\\u00e9]", "\u{e9}", true),
        ("\\$", "$", true),
        ("a{2}", "aa", true),
        ("a{2}", "a", false),
        ("a{2,}?", "aa", true),
        ("(a|bc)\\1", "bcbc", true),
        ("(a|bc)\\1", "abc", false),
        ("(?i)(a)\\1", "aA", true),
        ("x*", "", true),
        ("^", "", true),
        ("$", "", true),
        ("(?<=\\d{2})x", "12x", true),
        ("(?<=\\d{2})x", "1x", false),
        ("(a)?(?(1)b|c)+d", "abbd", true),
        ("(a)?(?(1)b|c)+d", "ccd", true),
        ("(a)?(?(1)b|c)+d", "abcd", true),
        ("(?:a|b)*c", "abac", true),
        ("(a)*b", "aab", true),
        ("(?=a)*a", "a", true),
        ("(?:a*)*b", "aab", true),
        ("(?:(?:a)?)+$", "aa", true),
        ("(?:x$)?", "x\n", true),
        ("(?:\\b)+a", " a", true),
        ("((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((a)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*b", "aab", true),
        ("((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((a)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*)*b", "b", true),
        ("(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:(?:a|b))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))", "b", true),
        ("(?i)I", "\u{131}", true),
        ("(?i)I", "i", true),
        ("(?i)\u{130}", "i", true),
        ("(?i)\u{130}", "I", true),
        ("(?i)s", "\u{17f}", true),
        ("(?i)k", "\u{212a}", true),
        ("(?i)\u{df}", "\u{1e9e}", true),
        ("(?i)\u{3c3}", "\u{3c2}", true),
        ("(?i)\u{3c3}", "\u{3a3}", true),
        ("(?i)[a-z]", "\u{212a}", true),
        ("(?i)[a-z]", "\u{130}", true),
        ("(?i)[^k]", "\u{212a}", false),
        ("(?i)[^k]", "x", true),
        ("(?ai:S)", "\u{17f}", false),
        ("(?ai:S)", "s", true),
        ("(?ai:[J-L])", "\u{212a}", false),
        ("(?ai:[J-L])", "k", true),
        ("(?i)(I)\\1", "I\u{131}", false),
        ("(?i)(I)\\1", "Ii", true),
        ("(?a:\\S)", "\u{a0}", false),
        ("(?a:\\S)", "x", true),
        ("(?a:[^\\d\\s])", "\u{a0}", false),
        ("(?a:\\s|x)", "\u{a0}", false),
        ("(?u:\\s)", "\u{a0}", true),
        ("(?a)(?u:\\s)", "\u{a0}", false),
        ("(?P<n>a)?+(?(n)){2,}", "-_", true),
        ("(?P<n>){0}\\1+", "a", false),
        ("(?=|(?P<n>)?){1,2}?\\1+?", "a", false),
        ("(a)(?<=\\1)", "aa", true),
        ("(a)(?<=\\1)", "ab", true),
        ("(?<=(a))\\1", "aa", true),
        ("(?:)+a", "a", true),
        ("(?:b|\\w{1000})", "b", true),
        ("(?:b|\\w{1000})", "a", false),
        (".{65535}", "x", false),
        ("(?<=a{3})b", "aaab", true),
        ("(?<=a{3})b", "aab", false),
    ]
    .into_iter()
    .filter(|&(pattern, text, found)| compile(pattern, 986).map(|compiled| compiled.search(text)) != Ok(found))
    .collect::<Vec<_>>();
    assert!(wrong.is_empty(), "{wrong:?}");
}

#[test]
fn a_deep_pattern_stops_where_python_stops() {
    let nest = |open: &str, close: &str, count: usize| format!("{}a{}", open.repeat(count), close.repeat(count));
    for (open, close, count, frames) in [("(", ")", 492, 986), ("(?:", ")*", 492, 986), ("(?(1)", ")", 984, 986), ("(", ")", 490, 982), ("(?(1)", ")", 980, 982)] {
        assert_ne!(compile(&format!("(a){}", nest(open, close, count)), frames).err().as_deref(), Some(RECURSION), "{open} {count}");
        assert_eq!(compile(&format!("(a){}", nest(open, close, count + 1)), frames).err().as_deref(), Some(RECURSION), "{open} {count}");
    }
}
